namespace: home

resources:
- mysql.yaml
- nextcloud.yaml
- portfolio.yaml
- react-express.yaml

secretGenerator:
  - name: mysql-secret
    files:
      - mysql-secret=./.secret-mysql

secretGenerator:
  - name: env-secret
    env: .env
    type: Opaque