apiVersion: v1
kind: Namespace
metadata:
  name: home
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: nextcloud
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - image: nextcloud:28
        name: nextcloud
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: MYSQL_HOST
        volumeMounts:
        - name: nextcloud-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: nextcloud-persistent-storage
        persistentVolumeClaim:
          claimName: nextcloud-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi