---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  template:
    spec:
      containers:
      - name: portfolio
        image: $(PORTFOLIO_IMAGE)
      imagePullSecrets:
        - name: oracle-docker-registry