apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio
  namespace: home
  annotations:
    kubernetes.io/ingress.class: nginx  # Specifies the Ingress Controller
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - portfoliohost
    secretName: portfoliotlssecret
  rules:
    - host: portfoliohost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 8000