apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-express
  namespace: home
  annotations:
    kubernetes.io/ingress.class: nginx  # Specifies the Ingress Controller
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - reactexpresshost
    secretName: reactexpresstlssecret
  rules:
    - host: reactexpresshost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-express
                port:
                  number: 8000